### ISSUE TITLE
U17 U18 E-Fuse and Switching Regulator Missing from board

### ISSUE THREAD

**Issue by davinbirdi** [UBC-Rocket/WB-AV-4510-CAN#10]
**U17: E-Fuse (TPS26600PWPR)**
https://www.digikey.ca/en/products/detail/texas-instruments/TPS26600PWPR/6199305?s=N4IgTCBcDaICoAUDKYBsqAMGEHUECUQBdAXyA  
https://www.ti.com/lit/ds/symlink/tps2660.pdf?HQS=dis-dk-null-digikeymode-dsf-pf-null-wwe&ts=1635100487170

**U18: Voltage Regulator**
https://www.digikey.ca/en/products/detail/semtech-corporation/TS30042-M050QFNR/6605522

U17 is E-Fuse that inputs in the 7s net and outputs to the 7s_F net (presumably fused).
U18 is a Voltage regulator that inputs the 7s_F net and outputs to PG (then to 3.3V) and 5.5V

ToDo: Currently cannot connect 24V or 7s to board to power microcontroller and also toggle 24V outputs. Will look at getting the parts and adding to board.

Note: U1 also missing will do separate Issue

**Comment by davinbirdi** [comment]
24V Output controlled via SPI
https://www.nxp.com/docs/en/data-sheet/MC06XS4200.pdf

**Comment by misprit7** [comment]
For now we can just power the board and high side switch separately, so this isn't the end of the world. For the next iteration of the PCB we'll place them.
