### ISSUE TITLE
Floating Analog Ground & VREFL

### ISSUE THREAD

**Issue by davinbirdi** [UBC-Rocket/WB-AV-4510-CAN#18]
Pin 33 is the VREFL for on-chip ADCs. 

When reading from ADCs there is an offset of 800mv where it reads 0 and is consistent. The issue is being unable to measure below 800mV as the range only goes to -253 which stops at ~600mV.

Read page 1000 of the [big manual for application information.](https://www.pjrc.com/teensy/K66P144M180SF5RMV2.pdf)

We have temporarily connected a wire between this point and ground, but for the next revision please connect the via that seems to have been forgotten to be connected to the ground plane. 

> <img width="780" alt="image" src="https://user-images.githubusercontent.com/24193569/151602641-97e3b44c-11af-4c18-91a5-5260c7236e83.png">
 

<img width="200" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/24193569/151601542-f83162ac-3c56-4121-b85a-3cc2be1e7bc1.png">

**Comment by misprit7** [comment]
Fixed this, now AGND is tied directly to GND.
