### ISSUE TITLE
Verify High-Side Switches are output to the correct pins of connectors

### ISSUE THREAD

**Issue by davinbirdi** [UBC-Rocket/WB-AV-4510-CAN#22]
<img width="626" alt="image" src="https://user-images.githubusercontent.com/24193569/155896476-1c96c691-73c6-40e1-a856-e98b1c311942.png">

This looks nets aren't connected properly. If it is specifically done this way, it's all good; but it's not it might be better to have fixed.

**Comment by misprit7** [comment]
This has been fixed, this was a result of the high side switch mixup.
