### ISSUE TITLE
Purchase PCB

### ISSUE THREAD

**Issue by misprit7** [UBC-Rocket/WB-AV-4510-CAN#26]
Buy the Rev C PCB from JLCPCB.

**Comment by misprit7** [comment]
I want to do a review of both this and the FC tomorrow before we order though.

**Comment by Esouder** [comment]
Final checks:

- [x] Hi-side switch pins
- [x] ADC MISO/MOSI
- [x] TC Pullups
- [x] Test point movement

**Comment by Esouder** [comment]
🎉🎉🎉
